# Generated by Django 5.2.7 on 2025-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_myuser_options_myuser_date_joined_myuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='ads_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='earned',
            field=models.FloatField(default=0.0),
        ),
    ]
